
import argparse, pandas as pd, spotipy
from spotipy.oauth2 import SpotifyOAuth

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--csv", required=True, help="CSV with 'track_id' column")
    ap.add_argument("--public", action="store_true", help="Create as public (default private)")
    ap.add_argument("--description", default="Generated by Playlist Auto-DJ")
    args = ap.parse_args()

    df = pd.read_csv(args.csv)
    if "track_id" not in df.columns:
        raise SystemExit("CSV must include track_id column.")

    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope="playlist-modify-private,playlist-modify-public"))
    user_id = sp.current_user()["id"]
    pl = sp.user_playlist_create(user=user_id, name=args.name, public=args.public, description=args.description)
    uris = ["spotify:track:"+tid for tid in df["track_id"].astype(str).tolist()]
    for i in range(0, len(uris), 100):
        sp.playlist_add_items(pl["id"], uris[i:i+100])
    print(f"Created: {pl.get('external_urls',{}).get('spotify','(open in Spotify)')}")

if __name__ == "__main__":
    main()
